server:
  port: 8093
  servlet:
    context-path: /
spring:
  application:
    name: InventoryService
  datasource:
#    url: jdbc:postgresql://localhost:5432/inventory9?CreateDatabaseIfNotExist=true
    url: postgres://ec2-54-74-95-84.eu-west-1.compute.amazonaws.com:5432/d9af3jns9hd465
#    username: postgres
    username: uzonculekybrqc
#    password: admin
    password: e95856dcc9330ed1ed23fad4be1464e4cfd4abda8198461c68a9c8207126a6f5
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        namingStrategy: org.hibernate.cfg.PhysicalNamingStrategy
  cloud:
    discovery:
      enabled: false
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
logging:
  level:
    '[com.ros.inventory]': DEBUG
